services:
  orchestrator:
    build:
      context: .
      dockerfile: cmd/orchestrator/Dockerfile
    ports:
      - "8080:8080"
    environment:
      TIME_ADDITION_MS: 100
      TIME_SUBTRACTION_MS: 100
      TIME_MULTIPLICATIONS_MS: 200
      TIME_DIVISIONS_MS: 200
    networks:
      - calculator-network

  agent:
    build:
      context: .
      dockerfile: cmd/agent/Dockerfile
    environment:
      COMPUTING_POWER: 4
      ORCHESTRATOR_URL: http://orchestrator:8080
    depends_on:
      - orchestrator
    command: sh -c "sleep 5 && ./agent"
    networks:
      - calculator-network

networks:
  calculator-network:
    driver: bridge